version: '3.3'
services:
    portal-mariadb:
        container_name: portal-mariadb
        image: yobasystems/alpine-mariadb:latest
        environment:
            - MYSQL_ROOT_PASSWORD=secr3t
            - MYSQL_USER=user
            - MYSQL_DATABASE=portal
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=secr3t
        # volumes:
        #     - ./volume/data:/var/lib/mysql
        ports:
           - "3306:3306"
