
version: '3.3'
services:
    portal:
        image: tykio/portal:v0.0.1-rc16
        ports:
            - "3001:3001"
        environment:
            - "PORTAL_LICENSEKEY=${TYK_DB_LICENSEKEY}"
            - ADMIN_EMAIL=auto_test@tyk.io
            - ADMIN_PASSWORD=test123
            - PORTAL_DATABASE_DIALECT=postgres
            - "PORTAL_DATABASE_CONNECTIONSTRING=host=portal-postgres port=5432 user=admin dbname=portal password=secr3t sslmode=disable"
        command: "-bootstrap"
        depends_on:
            - portal-postgres

    portal-postgres:
        image: postgres:10-alpine
        restart: on-failure:5
        environment:
            - POSTGRES_PASSWORD=secr3t
        volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql