version: "3.7"
services:
  selenoid:
    image: "aerokube/selenoid:latest"
    container_name: selenoid
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4444:4444"
    volumes:
      - /Users/konrad/go/src/github.com/TykTechnologies/portal-tests/video/:/opt/selenoid/video/
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/Users/konrad/go/src/github.com/TykTechnologies/portal-tests/video/


# this is the custom build app which contains our automation test scripts
  e2e:
    image: e2e-test
    build: . # it takes the path of the dockerfile and builds it
    depends_on:
      - selenoid
    links:
      - selenoid
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # volumes:
    #   - "./allure-results:/usr/lib/wdio/allure-results" # volume mapping the allure results
networks:
  default:
    external: false
    name: tyk-test