version: "3.5"
services:
  e2e:
    image: e2e-test
    build: .
    volumes:
      # - "./results:/usr/lib/wdio/results" # volume mapping the time-line results
      - .:/usr/lib/wdio/ # volume mapping the code of framewrk
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/London # adding timezone
      - DOCKER_EXECUTION=true
      - SELENOID=true
      - HOST_IP=${HOST_IP}
      - ARA_TYK=${ARA_TYK}
    command: "npm run docker-test"

networks:
  default:
    external: false
    name: tyk-test