version: "3"
services:
  chrome:
    image: seleniarm/node-chromium:105.0
    # image: selenium/node-chrome:105.0-20220831
    shm_size: 2gb
    depends_on:
      - selenium-hub
    networks:
      - tyk-test
    extra_hosts:
      - "host.docker.internal:host-gateway"           
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=3
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=

  selenium-hub:
    image: selenium/hub:4.4.0
    container_name: selenium-hub
    networks:
      - tyk-test
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

networks:
    tyk-test:
        external: true
