version: '3.1'

services:

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secr3t
      MYSQL_DATABASE: portal
      MYSQL_USER: admin
      MYSQL_PASSWORD: secr3t
    ports:
      - "3306:3306"

