version: '3.1'

services:

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secr3t
    ports:
      - "3306:3306"
    volumes:
      - ./volume/data:/var/lib/mysql
