version: '3.3'
services:
    portal:
        image: tykio/portal:${PORTAL_IMAGE_VERSION}
        ports:
            - "3001:3001"
        environment:
            - "PORTAL_LICENSEKEY=${TYK_DB_LICENSEKEY}"
            - ADMIN_EMAIL=auto_test@tyk.io
            - ADMIN_PASSWORD=test123
            - PORTAL_DATABASE_DIALECT=${PORTAL_DATABASE_DIALECT}
            - PORTAL_DATABASE_CONNECTIONSTRING=${PORTAL_DATABASE_CONNECTIONSTRING}
        command: --bootstrap
    tyk-dashboard:
        container_name: tyk-dashboard-local
        image: tykio/tyk-dashboard:v3.2.1
        ports:
            - "3000:3000"
        environment:
            - TYK_LOGLEVEL=info
            - "TYK_DB_LICENSEKEY=${TYK_DB_LICENSEKEY}"
        volumes:
            - ./tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf
        depends_on:
            - tyk-redis
            - tyk-mongo
    tyk-gateway:
        container_name: tyk-gateway-local
        image: tykio/tyk-gateway:v3.2.1
        ports:
            - "8081:8081" 
        volumes:
            - ./tyk.conf:/opt/tyk-gateway/tyk.conf
        environment:
            - TYK_LOGLEVEL=info
        depends_on:
            - tyk-redis
    tyk-redis:
        container_name: tyk-redis
        image: redis:6
        volumes:
            - ./redis-volume/data:/data
        ports:
            - "6379:6379"
    tyk-mongo:
        image: mongo:4.1
        volumes:
            - ./mongo-volume/data:/data/db
        ports:
           - "27017:27017"
    mailhog:
        image: mailhog/mailhog
        ports:
           - "8025:8025"
           - "1025:1025"
    keycloak-postgres:
        image: postgres:10-alpine
        restart: on-failure:5
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=keycloak
            - POSTGRES_USER=keycloak
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            - ./keycloak-db/data:/var/lib/postgresql/data
    keycloak: 
        image: jboss/keycloak:16.1.0
        container_name: keycloak
        environment:
            # - KEYCLOAK_USER=admin
            # - KEYCLOAK_PASSWORD=admin
            - DB_USER=keycloak
            - DB_PASSWORD=password
            - DB_ADDR=keycloak-postgres
            - DB_VENDOR=postgres
            - KEYCLOAK_FRONTEND_URL=http://localhost:8080/auth
        ports:
            - "8080:8080"
        # volumes:
        #     - ./keycloak/:/opt/jboss/keycloak/standalone/data/
        networks:
            - default
        depends_on:
            - keycloak-postgres
networks:
  default:
    name: portal