version: '3.3'
services:
    keycloak-postgres:
        image: postgres:10-alpine
        # restart: on-failure:5
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=keycloak
            - POSTGRES_USER=keycloak
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            - ./keycloak-db/data:/var/lib/postgresql/data
    keycloak: 
        image: jboss/keycloak:16.1.0
        container_name: keycloak
        environment:
            # - KEYCLOAK_USER=admin
            # - KEYCLOAK_PASSWORD=admin
            - DB_USER=keycloak
            - DB_PASSWORD=password
            - DB_ADDR=keycloak-postgres
            - DB_VENDOR=postgres
            - KEYCLOAK_FRONTEND_URL=http://localhost:8080/auth
        ports:
            - "8080:8080"
        # volumes:
        #     - ./keycloak/:/opt/jboss/keycloak/standalone/data/
        networks:
            - default
        depends_on:
            - keycloak-postgres

networks:
  default:
    external: false
    name: tyk-test